name: GitHub Actions

on: [push]

jobs:
  build-lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install @angular/cli
      run: |
        npm ci -g @angular/cli@latest

    - name: Install dependencies
      run: |
        npm ci

    - name: Build EASY
      run: |
        npm run build --if-present

    - name: Lint EASY and docs ts files
      run: |
        npm run lint --if-present

    - name: Lint EASY and docs scss files
      run: |
        npm run lint:scss --if-present

    - name: Test EASY and docs
      run: |
        npm run test-all --if-present

    - name: Upload coverage reports for EASY and docs
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

    - name: Deploy docs
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npm run deploy
