name: Build and test

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install
      run: |
        npm i -g npm@latest --silent
        npm i -g @angular/cli@latest --silent
        npm i --silent

    - name: Build
      run: |
        npm run build

    - name: Lint
      run: |
        npm run lint

    - name: Test
      run: |
        npm run test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v2.1.0
      with:
        flags: docs,easy
        name: codecov
        fail_ci_if_error: true

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run deploy
