name: GitHub Actions

on: [push]

jobs:
  build-lint-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install @angular/cli
      run: |
        npm i -g @angular/cli@latest --silent

    - name: Install dependencies
      run: |
        npm i --silent

    - name: Build EASY
      run: |
        npm run build:easy

    - name: Lint EASY and docs
      run: |
        npm run lint

    - name: Test EASY and docs
      run: |
        npm run test

    - name: Upload test coverage reports for EASY and docs
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true

    - name: Deploy docs
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npm run deploy

    - name: Publish EASY
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{secrets.NPM_AUTH_TOKEN}}
        package: ./projects/easy-framework/package.json
